directories:
  output: installer-dist-standalone
  buildResources: assets
appId: com.reduxion.launcher.installer
productName: Reduxion Launcher Installer
copyright: Copyright © 2025 Reduxion Team
files:
  - filter:
      - installer-standalone.html
      - installer-standalone-main.js
      - package.json
      - fonts/**/*
asar: true
asarUnpack: []
extraMetadata:
  main: installer-standalone-main.js
win:
  target:
    - target: portable
      arch:
        - x64
  icon: build/icon.png
  artifactName: ReduxionLauncherInstaller.exe
portable:
  artifactName: ReduxionLauncherInstaller.exe
electronVersion: 25.0.0
